### ISSUE TITLE
Referencing main.dart.js from other folder

### ISSUE THREAD

**Issue by ivanfeanor** [jakemac53/built_html#11]
Hi. Starting new project - my main.dart is located in /lib/ with other packages there as well.
In web there is just index.html
flutter build web works fine.
flutter build web
Compiling lib/main.dart for the Web...                             19.4s

But if i try 
flutter pub run build_runner build --output out
i got this error
[INFO] Generating build script...
[INFO] Generating build script completed, took 382ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 194ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 853ms

[INFO] Running build...
[SEVERE] built_html:built_html on web/index.template.html:

AssetNotFoundException: PROJECT|web/main.dart.js
[INFO] Running build completed, took 303ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 126ms

[SEVERE] Failed after 440ms

Could you advice me on the settings or how should i refference the main.dart.js that is not within the web folder?

**Comment by jakemac53** [comment]
This uses the [AssetId.resolve](https://pub.dev/documentation/build/latest/build/AssetId/AssetId.resolve.html) api - so it supports `package:` uris and `asset:` uris - either would work for you in this case: `package:<your-package>/<path>/<under>/<lib>` or `asset:<your-package>/lib/<path>/<under>/<lib>`.

**Comment by jakemac53** [comment]
To further clarify, you would pass this as the argument to `digest` - so something like:

```
{{digest package:<your-package>/main.dart.js}}
```

**Comment by ivanfeanor** [comment]
Hello, @jakemac53 . Thanks for the quick response. Sorry, but it is still not working.
`pub run build_runner build --output out
Precompiling executable...
Precompiled build_runner:build_runner.
[INFO] Generating build script...
[INFO] Generating build script completed, took 368ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 10.3s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 1.2s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[SEVERE] built_html:built_html on web/index.template.html:

AssetNotFoundException: Vivescia|lib/main.dart.js
[INFO] Running build completed, took 585ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 133ms

[SEVERE] Failed after 729ms
pub finished with exit code 1`
in pubspec it seems to be right
`cat pubspec.yaml
name: Vivescia`
also right in cat .dart_tool/package_config.json
`..
    {
      "name": "Vivescia",
      "rootUri": "../",
      "packageUri": "lib/",
      "languageVersion": "2.7"
    }
..`
I was able to get in compelte run with   
`<script src="main.dart.js?q={{digest package:Vivescia/main.dart}}" type="application/javascript"></script>`
But it is only calculate digetst of main.dart intself, not compiled. And no other build artifact exist in output directory

`pwd
...vivescia/out/web
feanor@Ivans-iMac web % ls -l
total 32
-rw-r--r--   1 feanor  staff  1672  5 авг 12:14 favicon.png
drwxr-xr-x  14 feanor  staff   448  5 авг 12:14 icons
-rw-r--r--   1 feanor  staff  1659  5 авг 12:14 index.html
-rw-r--r--   1 feanor  staff  1664  5 авг 12:14 index.template.html
-rw-r--r--   1 feanor  staff   600  5 авг 12:14 manifest.json
lrwxr-xr-x   1 feanor  staff    11  5 авг 12:14 packages -> ../packages`

So, it seems like the issue maybe related to the build phase - that we dont actually get the builded app and thats why there is error in search?
here is my env
`[✓] Flutter (Channel beta, 1.20.0-7.4.pre, on Mac OS X 10.15.4 19E287, locale en-RU)
    • Flutter version 1.20.0-7.4.pre at /Users/feanor/Work/SourceCode/flutter
    • Framework revision 916c3ac648 (4 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)`

**Comment by jakemac53** [comment]
Oh - @ivanfeanor this package likely no longer works for flutter web apps at all. They do javascript compilation totally separate from the `build` package now as a separate step which runs later. The JS files are thus not accessible to this builder :/.

I would file an issue on the flutter repo if you need the same functionality from flutter web.

**Comment by ivanfeanor** [comment]
@jakemac53 yeah, i would appreciate that. Do you think it is feasible somehow?

**Comment by jakemac53** [comment]
You would have to ask on the flutter issue tracker, they would need to create some other solution for you
